### ISSUE TITLE
Outdated IDM version and a suggestion

### ISSUE THREAD

**Issue by Dhyfer1** [dokimkhanh/IDM-Activate#1]
Hi @dokimkhanh 

IDM has recently been updated to version 6.40 build 10, please update the executable file.

Another thing, can you create a bat file to reset the IDM trial period? I am using [idm-trial-reset](https://github.com/J2TEAM/idm-trial-reset), but the problem with idm-trial-reset is that although I can still download with IDM after the trial period is over, I get popup windows saying "Your trial period is over" and "Register the program", these popup windows always appear before starting any download and it's very annoying to see those windows every time I download something.

On Github, [IDM-reset](https://github.com/Jackpison/IDM-reset), is also popular, but it also has the problem of pop-up windows before downloading.

When I was using version 6.40 build 8, I downloaded the IDMan.exe file from your repository and placed it in the IDM install folder, then I downloaded something on the internet and didn't get any popups, but then I updated IDM to the latest version that came out a couple of days ago (6.40 build 10) and the trial period ended popups came back.

Why the description in your repository says: "A small program to help activate IDM license" if it' s not an activator? it seems to me that it's just the patched IDM executable file. 

Anyway, can you update the executable to the latest version and/or create a bat file to reset IDM?

**Comment by dokimkhanh** [comment]
> Hi @dokimkhanh
> 
> IDM has recently been updated to version 6.40 build 10, please update the executable file.
> 
> Another thing, can you create a bat file to reset the IDM trial period? I am using [idm-trial-reset](https://github.com/J2TEAM/idm-trial-reset), but the problem with idm-trial-reset is that although I can still download with IDM after the trial period is over, I get popup windows saying "Your trial period is over" and "Register the program", these popup windows always appear before starting any download and it's very annoying to see those windows every time I download something.
> 
> On Github, [IDM-reset](https://github.com/Jackpison/IDM-reset), is also popular, but it also has the problem of pop-up windows before downloading.
> 
> When I was using version 6.40 build 8, I downloaded the IDMan.exe file from your repository and placed it in the IDM install folder, then I downloaded something on the internet and didn't get any popups, but then I updated IDM to the latest version that came out a couple of days ago (6.40 build 10) and the trial period ended popups came back.
> 
> Why the description in your repository says: "A small program to help activate IDM license" if it' s not an activator? it seems to me that it's just the patched IDM executable file.
> 
> Anyway, can you update the executable to the latest version and/or create a bat file to reset IDM?

Hi, this project is under construction, the software is being fixed due to some glitches during testing. I will upload the finished version soon

**Comment by Dhyfer1** [comment]
> Hi, this project is under construction, the software is being fixed due to some glitches during testing. I will upload the finished version soon

Hi. Thanks for the activator, I used the 'Trial Reset' option but it did nothing, because the annoying pop-ups still appear, then I used the 'Register' option and IDM was registered with my name, but the annoying pop-ups still appear, this time a new pop-up window appears saying "internet download manager has been registered with a fake serial number or the serial number has been blocked".

So I decided to use instead, again, your IDMan.exe file. I noticed that since the previous version (6.40 build 8) if I replace the original IDMan file with the same file from your repository, I don't get any popup windows when I download, so the IDMan file is working fine, and the activator registers the program but I still get popup windows. 

By the way, a new version of IDM is out. 6.40 build 11. Please update the file

**Comment by dokimkhanh** [comment]
> > Hi, this project is under construction, the software is being fixed due to some glitches during testing. I will upload the finished version soon
> 
> Hi. Thanks for the activator, I used the 'Trial Reset' option but it did nothing, because the annoying pop-ups still appear, then I used the 'Register' option and IDM was registered with my name, but the annoying pop-ups still appear, this time a new pop-up window appears saying "internet download manager has been registered with a fake serial number or the serial number has been blocked".
> 
> So I decided to use instead, again, your IDMan.exe file. I noticed that since the previous version (6.40 build 8) if I replace the original IDMan file with the same file from your repository, I don't get any popup windows when I download, so the IDMan file is working fine, and the activator registers the program but I still get popup windows.
> 
> By the way, a new version of IDM is out. 6.40 build 11. Please update the file

Updated @Dhyfer1

**Comment by Dhyfer1** [comment]
> Updated @Dhyfer1

Thank you for updating the file to the new version. So I have downloaded and unzipped the file for the new version of IDM from the repository, I run the IDM-Activate.exe file but I get a message from Windows Defender warning that the file contains a trojan, so I disable the antivirus protection, run the activator again, put my name and email and activate IDM. I open IDM and it shows that it is registered, but when I want to download it simply doesn't open the IDM download window and the download doesn't start even in the browser.

So, just like in version 6.40 build 10, I replace the original IDMan.exe file with the same IDMan file that comes inside the zip and when I do this I can download without popups.

Your activator is based on the J2TEAM activator, but if you look at the idm-trial-reset [issues](https://github.com/J2TEAM/idm-trial-reset/issues) you can see that their activator isn't working as reported by several users. 

In exchange for a activator, couldn't you just make a bat file like [Jackpison's](https://github.com/Jackpison/IDM-reset) that removes all the modifications made by IDM? that way, I think, you don't have to create a new activator or IDMan file every time IDM is updated to a new version.

**Comment by dokimkhanh** [comment]
> > Updated @Dhyfer1
> 
> Thank you for updating the file to the new version. So I have downloaded and unzipped the file for the new version of IDM from the repository, I run the IDM-Activate.exe file but I get a message from Windows Defender warning that the file contains a trojan, so I disable the antivirus protection, run the activator again, put my name and email and activate IDM. I open IDM and it shows that it is registered, but when I want to download it simply doesn't open the IDM download window and the download doesn't start even in the browser.
> 
> So, just like in version 6.40 build 10, I replace the original IDMan.exe file with the same IDMan file that comes inside the zip and when I do this I can download without popups.
> 
> Your activator is based on the J2TEAM activator, but if you look at the idm-trial-reset [issues](https://github.com/J2TEAM/idm-trial-reset/issues) you can see that their activator isn't working as reported by several users.
> 
> In exchange for a activator, couldn't you just make a bat file like [Jackpison's](https://github.com/Jackpison/IDM-reset) that removes all the modifications made by IDM? that way, I think, you don't have to create a new activator or IDMan file every time IDM is updated to a new version.

Thank u

**Comment by Dhyfer1** [comment]
What are you thanking me for? For telling you that only the IDMan file works or for the bat file suggestion?
